#!/usr/bin/env python3
"""Regenerate the bundled icon font + glyph constants.

Downloads the Tabler Icons webfont (MIT), subsets it to just the glyphs the app
uses, and writes:
  - src/CodeRev.App/Assets/coderev-icons.ttf   (a few KB, not the full 2.8 MB)
  - src/CodeRev.App/Controls/Icons.cs          (name -> glyph constants)

To add an icon: append its Tabler name (outline, no "-filled") to ICONS below
and rerun:  python tools/generate-icons.py   (needs:  pip install fonttools)
"""
import io
import os
import re
import urllib.request
from fontTools import subset
from fontTools.ttLib import TTFont

TABLER = "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3/dist"

# Icons used across the app (Tabler outline names).
ICONS = [
    "folder", "folder-open", "player-play", "player-stop", "info-circle",
    "settings", "file-download", "sun-moon", "language", "arrow-up", "arrow-left",
    "refresh", "circle-check", "loader-2", "circle-x", "alert-triangle",
    "git-branch", "git-pull-request", "chevron-down", "chevron-right", "file-diff",
    "history", "list", "file-text", "x", "search", "point", "square",
    "square-check", "external-link", "check",
]

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.normpath(os.path.join(HERE, "..", "src", "CodeRev.App"))
TTF_OUT = os.path.join(APP, "Assets", "coderev-icons.ttf")
CS_OUT = os.path.join(APP, "Controls", "Icons.cs")


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def codepoints(css_text):
    pairs, cur = {}, None
    for line in css_text.splitlines():
        s = line.strip()
        if s.startswith(".ti-") and ":before" in s:
            cur = s[4:s.index(":before")]
        elif cur and "content:" in s:
            m = re.search(r'content:\s*"\\([0-9a-fA-F]+)"', s)
            if m:
                pairs[cur] = m.group(1)
            cur = None
    return pairs


def main():
    css = fetch(TABLER + "/tabler-icons.css").decode("utf-8")
    cp_all = codepoints(css)
    missing = [n for n in ICONS if n not in cp_all]
    if missing:
        raise SystemExit("Unknown Tabler icon names: " + ", ".join(missing))
    cp = {n: cp_all[n] for n in ICONS}

    ttf_bytes = fetch(TABLER + "/fonts/tabler-icons.ttf")
    options = subset.Options()
    options.glyph_names = False
    font = subset.load_font(io.BytesIO(ttf_bytes), options)
    ss = subset.Subsetter(options=options)
    ss.populate(unicodes=[int(v, 16) for v in cp.values()])
    ss.subset(font)
    subset.save_font(font, TTF_OUT, options)

    family = TTFont(TTF_OUT)["name"].getDebugName(1)

    def pascal(n):
        return "".join(p.capitalize() for p in n.split("-"))

    lines = [
        "namespace CodeRev.App.Controls;",
        "",
        "/// <summary>",
        "/// Glyph constants for the bundled icon font (Assets/coderev-icons.ttf — a",
        "/// subset of Tabler Icons, MIT). Use with the IconFont resource, e.g.",
        "/// <c>&lt;TextBlock Classes=\"icon\" Text=\"{x:Static c:Icons.Folder}\"/&gt;</c>.",
        "/// Generated by tools/generate-icons.py — do not edit by hand.",
        "/// </summary>",
        "public static class Icons",
        "{",
    ]
    for n in ICONS:
        lines.append(f'    public const string {pascal(n)} = "\\u{cp[n].upper()}";')
    lines.append("}")
    with open(CS_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print(f"family={family}  glyphs={len(cp)}  ttf={os.path.getsize(TTF_OUT)} bytes")
    print("wrote", os.path.relpath(TTF_OUT, HERE), "and", os.path.relpath(CS_OUT, HERE))


if __name__ == "__main__":
    main()
