namespace CodeRev.App.Controls;

/// <summary>
/// Glyph constants for the bundled icon font (Assets/coderev-icons.ttf — a
/// subset of Tabler Icons, MIT). Use with the IconFont resource, e.g.
/// <c>&lt;TextBlock Classes="icon" Text="{x:Static c:Icons.Folder}"/&gt;</c>.
/// Generated by tools/generate-icons.py — do not edit by hand.
/// </summary>
public static class Icons
{
    public const string Folder = "\uEAAD";
    public const string FolderOpen = "\uFAF7";
    public const string PlayerPlay = "\uED46";
    public const string PlayerStop = "\uED4A";
    public const string InfoCircle = "\uEAC5";
    public const string Settings = "\uEB20";
    public const string FileDownload = "\uEA9D";
    public const string SunMoon = "\uF4A3";
    public const string Language = "\uEBBE";
    public const string ArrowUp = "\uEA25";
    public const string ArrowLeft = "\uEA19";
    public const string Refresh = "\uEB13";
    public const string CircleCheck = "\uEA67";
    public const string Loader2 = "\uF226";
    public const string CircleX = "\uEA6A";
    public const string AlertTriangle = "\uEA06";
    public const string GitBranch = "\uEAB2";
    public const string GitPullRequest = "\uEAB6";
    public const string ChevronDown = "\uEA5F";
    public const string ChevronRight = "\uEA61";
    public const string FileDiff = "\uECF1";
    public const string History = "\uEBEA";
    public const string List = "\uEB6B";
    public const string FileText = "\uEAA2";
    public const string X = "\uEB55";
    public const string Search = "\uEB1C";
    public const string Point = "\uEB0C";
    public const string Square = "\uEB2C";
    public const string SquareCheck = "\uEB28";
    public const string ExternalLink = "\uEA99";
    public const string Check = "\uEA5E";
}
